### ISSUE TITLE
Multiple connections to the same JDBC server not allowed

### ISSUE THREAD

**Issue by zevektor** [confluentinc/kafka-connect-jdbc#377]
In my use case I need to get new data from two tables on the same database.
These two tables have very different columns, so I need to write two different configurations for the JDBC source connector. 
Configurations are in the form:

```json
{
	"name": "schema.table", 
	"config": {
	"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
	"tasks.max":"1",
	"connection.url":"jdbc:prod:DBNAME@mms://dburl:dbport;FetchSize=1000",
	"topic.prefix":"schema.table",
	"query":"SELECT * FROM schema.table",
	"mode":"timestamp",
	"timestamp.column.name":"timestamp_column",
	"connection.user":"user",
	"connection.password":"password",
	"validate.non.null": "false",
	"key.converter": "org.apache.kafka.connect.json.JsonConverter",
	"key.converter.schemas.enable": "true",
	"value.converter": "org.apache.kafka.connect.json.JsonConverter",
	"value.converter.schemas.enable": "true" 
	}
}
```

Apparently I cannot have two configurations that try to access the same jdbc server on the same worker, this will return the following error when I get the connector status from the worker.

```json
{
    "name": "connector-table-2",
    "connector": {
        "state": "RUNNING",
        "worker_id": "worker-1:8083"
    },
    "tasks": [
        {
            "state": "FAILED",
            "trace": "java.lang.IllegalArgumentException: A metric named 'MetricName [name=offset-commit-max-time-ms, group=connector-task-metrics, description=The maximum time in milliseconds taken by this task to commit offsets., tags={connector=connector-table-2, task=0}]' already exists, can't register another one.\n\tat org.apache.kafka.common.metrics.Metrics.registerMetric(Metrics.java:532)\n\tat org.apache.kafka.common.metrics.Sensor.add(Sensor.java:256)\n\tat org.apache.kafka.common.metrics.Sensor.add(Sensor.java:241)\n\tat org.apache.kafka.connect.runtime.WorkerTask$TaskMetricsGroup.<init>(WorkerTask.java:328)\n\tat org.apache.kafka.connect.runtime.WorkerTask.<init>(WorkerTask.java:69)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.<init>(WorkerSourceTask.java:100)\n\tat org.apache.kafka.connect.runtime.Worker.buildWorkerTask(Worker.java:445)\n\tat org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:404)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:852)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1600(DistributedHerder.java:108)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:866)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:862)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)\n",
            "id": 0,
            "worker_id": "worker-1:8083"
        }
    ],
    "type": "source"
}
```

I've tried to delete both `connector-table-1` and `connector-table-2` and to change the order the connectors are created. If `connector-table-2` is created first, then `connector-table-1` will give the same error.

**Comment by rhauch** [comment]
This is a known issue (https://issues.apache.org/jira/browse/KAFKA-6252) that was fixed in AK 1.0.1 (available now) and will also be fixed in AK 1.1 (due out soon). You should be able to restart the worker to work around the problem with AK 1.0.

**Comment by robsonpeixoto** [comment]
I'm still having this problem. I'm using `confluentinc/cp-kafka-connect:5.4.1` docker image. I tried the version 5.3.3 too, but without  success.
```
java.lang.IllegalArgumentException: A metric named 'MetricName [name=records-lag, group=consumer-fetch-manager-metrics, description=The latest lag of the partition, tags={client-id=connector-consumer-s3-sink-1, topic=cep_input_ted_in_created, partition=0}]' already exists, can't register another one.
    at org.apache.kafka.common.metrics.Metrics.registerMetric(Metrics.java:564)
    at org.apache.kafka.common.metrics.Sensor.add(Sensor.java:284)
    at org.apache.kafka.common.metrics.Sensor.add(Sensor.java:260)
    at org.apache.kafka.clients.consumer.internals.Fetcher$FetchManagerMetrics.recordPartitionLag(Fetcher.java:1751)
    at org.apache.kafka.clients.consumer.internals.Fetcher$FetchManagerMetrics.access$1800(Fetcher.java:1632)
    at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:656)
    at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:603)
    at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1294)
    at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1225)
    at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:444)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:317)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```
