### ISSUE TITLE
Docker build fails on the master branch

### ISSUE THREAD

**Issue by yohei1126** [confluentinc/kafka-connect-jdbc#783]
Hi, I need to build master branch on Docker. I am using the following Docker file.
This fails agains the master branch. Please let me know if I miss something.
Thanks in advance.

```
FROM gradle:jdk8 AS builder

# Instll kafka-connect-jdbc from here
# confluent version of kafka need to be install before building common libraries
# https://github.com/confluentinc/kafka-connect-jdbc/wiki/FAQ
RUN curl https://github.com/confluentinc/kafka/archive/master.zip -L -o kafka.zip \
    && unzip kafka.zip -d /tmp \
    && cd /tmp/kafka-master/ \
    && ./gradlew clean installAll

# common libraries need to be installed before building JDBC Kafka connect
RUN apt update && \
    apt upgrade -y && \
    apt install maven -y
RUN curl https://github.com/confluentinc/common/archive/master.zip -L -o confluent-common.zip \
    && unzip ./confluent-common.zip -d /tmp/ \
    && cd /tmp/common-master/ \
    && mvn clean install

# JDBC Kafka connect: OOM issue is fixed on the master branch but new version has not been released yet.
# https://github.com/confluentinc/kafka-connect-jdbc/pull/758
RUN curl https://github.com/confluentinc/kafka-connect-jdbc/archive/master.zip -L -o kafka-connect-jdbc.zip \
    && unzip kafka-connect-jdbc.zip -d /tmp/ \
    && cd /tmp/kafka-connect-jdbc-master/ \
    && mvn clean package
```

I got these errors.

```
INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.confluent.connect.jdbc.JdbcSourceConnectorTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.845 s - in io.confluent.connect.jdbc.JdbcSourceConnectorTest
[INFO] Running io.confluent.connect.jdbc.dialect.DerbyDatabaseDialectTest
[WARNING] Tests run: 29, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.124 s - in io.confluent.connect.jdbc.dialect.DerbyDatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialectTest
[INFO] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 s - in io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.dialect.SqlServerDatabaseDialectTest
[INFO] Tests run: 27, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.048 s - in io.confluent.connect.jdbc.dialect.SqlServerDatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.dialect.OracleDatabaseDialectTest
[INFO] Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 s - in io.confluent.connect.jdbc.dialect.OracleDatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest
[ERROR] Tests run: 24, Failures: 9, Errors: 0, Skipped: 0, Time elapsed: 0.1 s <<< FAILURE! - in io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest
[ERROR] createThreeColTwoPk(io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest)  Time elapsed: 0.004 s  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<CREATE TABLE [`myTable` (
`pk1` INTEGER NOT NULL,
`pk2` INTEGER NOT NULL,
`col1` INTEGER NOT NULL,
PRIMARY KEY(`pk1`,`pk2`]))> but was:<CREATE TABLE ["myTable" (
"pk1" INTEGER NOT NULL,
"pk2" INTEGER NOT NULL,
"col1" INTEGER NOT NULL,
PRIMARY KEY("pk1","pk2"]))>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.createThreeColTwoPk(SqliteDatabaseDialectTest.java:211)

[ERROR] createOneColNoPk(io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest)  Time elapsed: 0.002 s  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<CREATE TABLE [`myTable` (
`col1`] INTEGER NOT NULL)> but was:<CREATE TABLE ["myTable" (
"col1"] INTEGER NOT NULL)>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.createOneColNoPk(SqliteDatabaseDialectTest.java:198)

[ERROR] alterAddOneCol(io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest)  Time elapsed: 0.001 s  <<< FAILURE!
org.junit.internal.ArrayComparisonFailure: arrays first differed at element [0]; expected:<ALTER TABLE [`myTable` ADD `newcol1`] INTEGER NULL> but was:<ALTER TABLE ["myTable" ADD "newcol1"] INTEGER NULL>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.alterAddOneCol(SqliteDatabaseDialectTest.java:226)
Caused by: org.junit.ComparisonFailure: expected:<ALTER TABLE [`myTable` ADD `newcol1`] INTEGER NULL> but was:<ALTER TABLE ["myTable" ADD "newcol1"] INTEGER NULL>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.alterAddOneCol(SqliteDatabaseDialectTest.java:226)

[ERROR] shouldBuildUpsertStatement(io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest)  Time elapsed: 0.002 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...ERT OR REPLACE INTO [`myTable`(`id1`,`id2`,`columnA`,`columnB`,`columnC`,`columnD`]) VALUES(?,?,?,?,?,?...> but was:<...ERT OR REPLACE INTO ["myTable"("id1","id2","columnA","columnB","columnC","columnD"]) VALUES(?,?,?,?,?,?...>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.shouldBuildUpsertStatement(SqliteDatabaseDialectTest.java:193)

[ERROR] alterAddTwoCol(io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest)  Time elapsed: 0.001 s  <<< FAILURE!
org.junit.internal.ArrayComparisonFailure: arrays first differed at element [0]; expected:<ALTER TABLE [`myTable` ADD `newcol1`] INTEGER NULL> but was:<ALTER TABLE ["myTable" ADD "newcol1"] INTEGER NULL>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.alterAddTwoCol(SqliteDatabaseDialectTest.java:231)
Caused by: org.junit.ComparisonFailure: expected:<ALTER TABLE [`myTable` ADD `newcol1`] INTEGER NULL> but was:<ALTER TABLE ["myTable" ADD "newcol1"] INTEGER NULL>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.alterAddTwoCol(SqliteDatabaseDialectTest.java:231)

[ERROR] upsert(io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest)  Time elapsed: 0.003 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...ERT OR REPLACE INTO [`Book`(`author`,`title`,`ISBN`,`year`,`pages`]) VALUES(?,?,?,?,?)> but was:<...ERT OR REPLACE INTO ["Book"("author","title","ISBN","year","pages"]) VALUES(?,?,?,?,?)>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.upsert(SqliteDatabaseDialectTest.java:238)

[ERROR] createOneColOnePk(io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest)  Time elapsed: 0.001 s  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<CREATE TABLE [`myTable` (
`pk1` INTEGER NOT NULL,
PRIMARY KEY(`pk1`]))> but was:<CREATE TABLE ["myTable" (
"pk1" INTEGER NOT NULL,
PRIMARY KEY("pk1"]))>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.createOneColOnePk(SqliteDatabaseDialectTest.java:204)

[ERROR] shouldBuildCreateQueryStatement(io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest)  Time elapsed: 0.001 s  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<CREATE TABLE [`myTable` (
`c1` INTEGER NOT NULL,
`c2` INTEGER NOT NULL,
`c3` TEXT NOT NULL,
`c4` TEXT NULL,
`c5` NUMERIC DEFAULT '2001-03-15',
`c6` NUMERIC DEFAULT '00:00:00.000',
`c7` NUMERIC DEFAULT '2001-03-15 00:00:00.000',
`c8` NUMERIC NULL,
`c9` INTEGER DEFAULT 1,
PRIMARY KEY(`c1`]))> but was:<CREATE TABLE ["myTable" (
"c1" INTEGER NOT NULL,
"c2" INTEGER NOT NULL,
"c3" TEXT NOT NULL,
"c4" TEXT NULL,
"c5" NUMERIC DEFAULT '2001-03-15',
"c6" NUMERIC DEFAULT '00:00:00.000',
"c7" NUMERIC DEFAULT '2001-03-15 00:00:00.000',
"c8" NUMERIC NULL,
"c9" INTEGER DEFAULT 1,
PRIMARY KEY("c1"]))>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.shouldBuildCreateQueryStatement(SqliteDatabaseDialectTest.java:120)

[ERROR] shouldBuildAlterTableStatement(io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest)  Time elapsed: 0.001 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<ALTER TABLE [`myTable` ADD `c1`] INTEGER NOT NULL> but was:<ALTER TABLE ["myTable" ADD "c1"] INTEGER NOT NULL>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.shouldBuildAlterTableStatement(SqliteDatabaseDialectTest.java:155)

[INFO] Running io.confluent.connect.jdbc.dialect.SapHanaDatabaseDialectTest
[INFO] Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in io.confluent.connect.jdbc.dialect.SapHanaDatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.dialect.VerticaDatabaseDialectTest
[INFO] Tests run: 22, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 s - in io.confluent.connect.jdbc.dialect.VerticaDatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.dialect.MySqlDatabaseDialectTest
[INFO] Tests run: 27, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.084 s - in io.confluent.connect.jdbc.dialect.MySqlDatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.dialect.DatabaseDialectsTest
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in io.confluent.connect.jdbc.dialect.DatabaseDialectsTest
[INFO] Running io.confluent.connect.jdbc.dialect.GenericDatabaseDialectTest
[INFO] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.856 s - in io.confluent.connect.jdbc.dialect.GenericDatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.dialect.SybaseDatabaseDialectTest
[INFO] Tests run: 27, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.106 s - in io.confluent.connect.jdbc.dialect.SybaseDatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.dialect.GenericDatabaseDialectTypeTest
[INFO] Tests run: 36, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.046 s - in io.confluent.connect.jdbc.dialect.GenericDatabaseDialectTypeTest
[INFO] Running io.confluent.connect.jdbc.dialect.Db2DatabaseDialectTest
[INFO] Tests run: 31, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 s - in io.confluent.connect.jdbc.dialect.Db2DatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.sink.DbStructureTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in io.confluent.connect.jdbc.sink.DbStructureTest
[INFO] Running io.confluent.connect.jdbc.sink.BufferedRecordsTest
[ERROR] Tests run: 10, Failures: 0, Errors: 9, Skipped: 0, Time elapsed: 0.045 s <<< FAILURE! - in io.confluent.connect.jdbc.sink.BufferedRecordsTest
[ERROR] testFlushSuccessNoInfo(io.confluent.connect.jdbc.sink.BufferedRecordsTest)  Time elapsed: 0.018 s  <<< ERROR!
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
        at io.confluent.connect.jdbc.sink.BufferedRecordsTest.testFlushSuccessNoInfo(BufferedRecordsTest.java:514)

[ERROR] testMultipleDeletesBatchedTogether(io.confluent.connect.jdbc.sink.BufferedRecordsTest)  Time elapsed: 0.005 s  <<< ERROR!
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
        at io.confluent.connect.jdbc.sink.BufferedRecordsTest.testMultipleDeletesBatchedTogether(BufferedRecordsTest.java:404)

[ERROR] testMultipleDeletesWithSchemaBatchedTogether(io.confluent.connect.jdbc.sink.BufferedRecordsTest)  Time elapsed: 0.003 s  <<< ERROR!
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
        at io.confluent.connect.jdbc.sink.BufferedRecordsTest.testMultipleDeletesWithSchemaBatchedTogether(BufferedRecordsTest.java:461)

[ERROR] insertThenTwoDeletesWithSchemaInBatchNoFlush(io.confluent.connect.jdbc.sink.BufferedRecordsTest)  Time elapsed: 0.004 s  <<< ERROR!
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
        at io.confluent.connect.jdbc.sink.BufferedRecordsTest.insertThenTwoDeletesWithSchemaInBatchNoFlush(BufferedRecordsTest.java:226)

[ERROR] testInsertModeUpdate(io.confluent.connect.jdbc.sink.BufferedRecordsTest)  Time elapsed: 0.002 s  <<< ERROR!
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
        at io.confluent.connect.jdbc.sink.BufferedRecordsTest.testInsertModeUpdate(BufferedRecordsTest.java:553)

[ERROR] insertThenDeleteWithSchemaThenInsertInBatchFlush(io.confluent.connect.jdbc.sink.BufferedRecordsTest)  Time elapsed: 0.003 s  <<< ERROR!
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
        at io.confluent.connect.jdbc.sink.BufferedRecordsTest.insertThenDeleteWithSchemaThenInsertInBatchFlush(BufferedRecordsTest.java:344)

[ERROR] insertThenDeleteThenInsertInBatchFlush(io.confluent.connect.jdbc.sink.BufferedRecordsTest)  Time elapsed: 0.003 s  <<< ERROR!
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
        at io.confluent.connect.jdbc.sink.BufferedRecordsTest.insertThenDeleteThenInsertInBatchFlush(BufferedRecordsTest.java:285)

[ERROR] correctBatching(io.confluent.connect.jdbc.sink.BufferedRecordsTest)  Time elapsed: 0.002 s  <<< ERROR!
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
        at io.confluent.connect.jdbc.sink.BufferedRecordsTest.correctBatching(BufferedRecordsTest.java:99)

[ERROR] insertThenDeleteInBatchNoFlush(io.confluent.connect.jdbc.sink.BufferedRecordsTest)  Time elapsed: 0.003 s  <<< ERROR!
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
        at io.confluent.connect.jdbc.sink.BufferedRecordsTest.insertThenDeleteInBatchNoFlush(BufferedRecordsTest.java:166)

[INFO] Running io.confluent.connect.jdbc.sink.PreparedStatementBinderTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in io.confluent.connect.jdbc.sink.PreparedStatementBinderTest
[INFO] Running io.confluent.connect.jdbc.sink.metadata.FieldsMetadataTest
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in io.confluent.connect.jdbc.sink.metadata.FieldsMetadataTest
[INFO] Running io.confluent.connect.jdbc.sink.JdbcSinkTaskTest
[ERROR] Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.066 s <<< FAILURE! - in io.confluent.connect.jdbc.sink.JdbcSinkTaskTest
[ERROR] putPropagatesToDbWithPkModeRecordValue(io.confluent.connect.jdbc.sink.JdbcSinkTaskTest)  Time elapsed: 0.014 s  <<< ERROR!
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
        at io.confluent.connect.jdbc.sink.JdbcSinkTaskTest.putPropagatesToDbWithPkModeRecordValue(JdbcSinkTaskTest.java:179)

[ERROR] putPropagatesToDbWithAutoCreateAndPkModeKafka(io.confluent.connect.jdbc.sink.JdbcSinkTaskTest)  Time elapsed: 0.017 s  <<< ERROR!
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
        at io.confluent.connect.jdbc.sink.JdbcSinkTaskTest.putPropagatesToDbWithAutoCreateAndPkModeKafka(JdbcSinkTaskTest.java:105)

[INFO] Running io.confluent.connect.jdbc.sink.JdbcDbWriterTest
[ERROR] Tests run: 11, Failures: 0, Errors: 11, Skipped: 0, Time elapsed: 0.137 s <<< FAILURE! - in io.confluent.connect.jdbc.sink.JdbcDbWriterTest
[ERROR] multiInsertWithKafkaPkFailsDueToUniqueConstraint(io.confluent.connect.jdbc.sink.JdbcDbWriterTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.sql.SQLException> but was<org.apache.kafka.common.config.ConfigException>
        at io.confluent.connect.jdbc.sink.JdbcDbWriterTest.writeSameRecordTwiceExpectingSingleUpdate(JdbcDbWriterTest.java:193)
        at io.confluent.connect.jdbc.sink.JdbcDbWriterTest.multiInsertWithKafkaPkFailsDueToUniqueConstraint(JdbcDbWriterTest.java:131)

[ERROR] autoCreateWithAutoEvolve(io.confluent.connect.jdbc.sink.JdbcDbWriterTest)  Time elapsed: 0.003 s  <<< ERROR!
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
        at io.confluent.connect.jdbc.sink.JdbcDbWriterTest.autoCreateWithAutoEvolve(JdbcDbWriterTest.java:99)

[ERROR] idempotentDeletes(io.confluent.connect.jdbc.sink.JdbcDbWriterTest)  Time elapsed: 0.002 s  <<< ERROR!
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
        at io.confluent.connect.jdbc.sink.JdbcDbWriterTest.idempotentDeletes(JdbcDbWriterTest.java:237)

[ERROR] insertDeleteSameRecord(io.confluent.connect.jdbc.sink.JdbcDbWriterTest)  Time elapsed: 0.003 s  <<< ERROR!
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
        at io.confluent.connect.jdbc.sink.JdbcDbWriterTest.insertDeleteSameRecord(JdbcDbWriterTest.java:284)

[ERROR] idempotentUpsertWithKafkaPk(io.confluent.connect.jdbc.sink.JdbcDbWriterTest)  Time elapsed: 0.003 s  <<< ERROR!
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
        at io.confluent.connect.jdbc.sink.JdbcDbWriterTest.writeSameRecordTwiceExpectingSingleUpdate(JdbcDbWriterTest.java:193)
        at io.confluent.connect.jdbc.sink.JdbcDbWriterTest.idempotentUpsertWithKafkaPk(JdbcDbWriterTest.java:136)

[ERROR] sameRecordNTimes(io.confluent.connect.jdbc.sink.JdbcDbWriterTest)  Time elapsed: 0.108 s  <<< ERROR!
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
        at io.confluent.connect.jdbc.sink.JdbcDbWriterTest.sameRecordNTimes(JdbcDbWriterTest.java:407)

[ERROR] idempotentUpsertWithRecordValuePk(io.confluent.connect.jdbc.sink.JdbcDbWriterTest)  Time elapsed: 0.002 s  <<< ERROR!
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
        at io.confluent.connect.jdbc.sink.JdbcDbWriterTest.writeSameRecordTwiceExpectingSingleUpdate(JdbcDbWriterTest.java:193)
        at io.confluent.connect.jdbc.sink.JdbcDbWriterTest.idempotentUpsertWithRecordValuePk(JdbcDbWriterTest.java:156)

[ERROR] insertDeleteInsertSameRecord(io.confluent.connect.jdbc.sink.JdbcDbWriterTest)  Time elapsed: 0.002 s  <<< ERROR!
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
        at io.confluent.connect.jdbc.sink.JdbcDbWriterTest.insertDeleteInsertSameRecord(JdbcDbWriterTest.java:329)

[ERROR] multiInsertWithRecordValuePkFailsDueToUniqueConstraint(io.confluent.connect.jdbc.sink.JdbcDbWriterTest)  Time elapsed: 0.002 s  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.sql.SQLException> but was<org.apache.kafka.common.config.ConfigException>
        at io.confluent.connect.jdbc.sink.JdbcDbWriterTest.writeSameRecordTwiceExpectingSingleUpdate(JdbcDbWriterTest.java:193)
        at io.confluent.connect.jdbc.sink.JdbcDbWriterTest.multiInsertWithRecordValuePkFailsDueToUniqueConstraint(JdbcDbWriterTest.java:151)

[ERROR] idempotentUpsertWithRecordKeyPk(io.confluent.connect.jdbc.sink.JdbcDbWriterTest)  Time elapsed: 0.002 s  <<< ERROR!
org.apache.kafka.common.config.ConfigException: Unknown configuration 'batch.max.rows'
        at io.confluent.connect.jdbc.sink.JdbcDbWriterTest.writeSameRecordTwiceExpectingSingleUpdate(JdbcDbWriterTest.java:193)
        at io.confluent.connect.jdbc.sink.JdbcDbWriterTest.idempotentUpsertWithRecordKeyPk(JdbcDbWriterTest.java:146)

[ERROR] multiInsertWithRecordKeyPkFailsDueToUniqueConstraint(io.confluent.connect.jdbc.sink.JdbcDbWriterTest)  Time elapsed: 0.002 s  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.sql.SQLException> but was<org.apache.kafka.common.config.ConfigException>
        at io.confluent.connect.jdbc.sink.JdbcDbWriterTest.writeSameRecordTwiceExpectingSingleUpdate(JdbcDbWriterTest.java:193)
        at io.confluent.connect.jdbc.sink.JdbcDbWriterTest.multiInsertWithRecordKeyPkFailsDueToUniqueConstraint(JdbcDbWriterTest.java:141)

[INFO] Running io.confluent.connect.jdbc.sink.SqliteHelperTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 s - in io.confluent.connect.jdbc.sink.SqliteHelperTest
[INFO] Running io.confluent.connect.jdbc.util.ExpressionBuilderTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in io.confluent.connect.jdbc.util.ExpressionBuilderTest
[INFO] Running io.confluent.connect.jdbc.util.IdentifierRulesTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in io.confluent.connect.jdbc.util.IdentifierRulesTest
[INFO] Running io.confluent.connect.jdbc.util.TimeZoneValidatorTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in io.confluent.connect.jdbc.util.TimeZoneValidatorTest
[INFO] Running io.confluent.connect.jdbc.util.CachedConnectionProviderTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.881 s - in io.confluent.connect.jdbc.util.CachedConnectionProviderTest
[INFO] Running io.confluent.connect.jdbc.source.TimestampIncrementingCriteriaTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 s - in io.confluent.connect.jdbc.source.TimestampIncrementingCriteriaTest
[INFO] Running io.confluent.connect.jdbc.source.JdbcSourceTaskUpdateTest
[INFO] Tests run: 26, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.281 s - in io.confluent.connect.jdbc.source.JdbcSourceTaskUpdateTest
[INFO] Running io.confluent.connect.jdbc.source.JdbcSourceTaskLifecycleTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.626 s - in io.confluent.connect.jdbc.source.JdbcSourceTaskLifecycleTest
[INFO] Running io.confluent.connect.jdbc.source.JdbcSourceTaskConversionTest
[INFO] Tests run: 62, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.59 s - in io.confluent.connect.jdbc.source.JdbcSourceTaskConversionTest
[INFO] Running io.confluent.connect.jdbc.source.JdbcSourceConnectorConfigTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.61 s - in io.confluent.connect.jdbc.source.JdbcSourceConnectorConfigTest
[INFO] Running io.confluent.connect.jdbc.source.TableQuerierTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 s - in io.confluent.connect.jdbc.source.TableQuerierTest
[INFO] Running io.confluent.connect.jdbc.source.TableMonitorThreadTest
Exception in thread "Thread-90" org.apache.kafka.connect.errors.ConnectException: Simulated error with the db.
        at io.confluent.connect.jdbc.source.TableMonitorThreadTest$1.answer(TableMonitorThreadTest.java:164)
        at io.confluent.connect.jdbc.source.TableMonitorThreadTest$1.answer(TableMonitorThreadTest.java:160)
        at org.easymock.internal.Result.answer(Result.java:133)
        at org.easymock.internal.ReplayState.invokeInner(ReplayState.java:61)
        at org.easymock.internal.ReplayState.invoke(ReplayState.java:47)
        at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:40)
        at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:101)
        at com.sun.proxy.$Proxy32.getConnection(Unknown Source)
        at io.confluent.connect.jdbc.source.TableMonitorThread.updateTables(TableMonitorThread.java:141)
        at io.confluent.connect.jdbc.source.TableMonitorThread.run(TableMonitorThread.java:76)
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.407 s - in io.confluent.connect.jdbc.source.TableMonitorThreadTest
[INFO] Running io.confluent.connect.jdbc.source.NumericMappingConfigTest
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in io.confluent.connect.jdbc.source.NumericMappingConfigTest
[INFO] Running io.confluent.connect.jdbc.source.TimestampIncrementingOffsetTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in io.confluent.connect.jdbc.source.TimestampIncrementingOffsetTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SqliteDatabaseDialectTest.alterAddOneCol:226->BaseDialectTest.verifyAlterAddOneCol:398 arrays first differed at element [0]; expected:<ALTER TABLE [`myTable` ADD `newcol1`] INTEGER NULL> but was:<ALTER TABLE ["myTable" ADD "newcol1"] INTEGER NULL>
[ERROR]   SqliteDatabaseDialectTest.alterAddTwoCol:231->BaseDialectTest.verifyAlterAddTwoCols:404 arrays first differed at element [0]; expected:<ALTER TABLE [`myTable` ADD `newcol1`] INTEGER NULL> but was:<ALTER TABLE ["myTable" ADD "newcol1"] INTEGER NULL>
[ERROR]   SqliteDatabaseDialectTest.createOneColNoPk:198->BaseDialectTest.verifyCreateOneColNoPk:372 expected:<CREATE TABLE [`myTable` (
`col1`] INTEGER NOT NULL)> but was:<CREATE TABLE ["myTable" (
"col1"] INTEGER NOT NULL)>
[ERROR]   SqliteDatabaseDialectTest.createOneColOnePk:204->BaseDialectTest.verifyCreateOneColOnePk:378 expected:<CREATE TABLE [`myTable` (
`pk1` INTEGER NOT NULL,
PRIMARY KEY(`pk1`]))> but was:<CREATE TABLE ["myTable" (
"pk1" INTEGER NOT NULL,
PRIMARY KEY("pk1"]))>
[ERROR]   SqliteDatabaseDialectTest.createThreeColTwoPk:211->BaseDialectTest.verifyCreateThreeColTwoPk:390 expected:<CREATE TABLE [`myTable` (
`pk1` INTEGER NOT NULL,
`pk2` INTEGER NOT NULL,
`col1` INTEGER NOT NULL,
PRIMARY KEY(`pk1`,`pk2`]))> but was:<CREATE TABLE ["myTable" (
"pk1" INTEGER NOT NULL,
"pk2" INTEGER NOT NULL,
"col1" INTEGER NOT NULL,
PRIMARY KEY("pk1","pk2"]))>
[ERROR]   SqliteDatabaseDialectTest.shouldBuildAlterTableStatement:155->BaseDialectTest.assertStatements:350 expected:<ALTER TABLE [`myTable` ADD `c1`] INTEGER NOT NULL> but was:<ALTER TABLE ["myTable" ADD "c1"] INTEGER NOT NULL>
[ERROR]   SqliteDatabaseDialectTest.shouldBuildCreateQueryStatement:120 expected:<CREATE TABLE [`myTable` (
`c1` INTEGER NOT NULL,
`c2` INTEGER NOT NULL,
`c3` TEXT NOT NULL,
`c4` TEXT NULL,
`c5` NUMERIC DEFAULT '2001-03-15',
`c6` NUMERIC DEFAULT '00:00:00.000',
`c7` NUMERIC DEFAULT '2001-03-15 00:00:00.000',
`c8` NUMERIC NULL,
`c9` INTEGER DEFAULT 1,
PRIMARY KEY(`c1`]))> but was:<CREATE TABLE ["myTable" (
"c1" INTEGER NOT NULL,
"c2" INTEGER NOT NULL,
"c3" TEXT NOT NULL,
"c4" TEXT NULL,
"c5" NUMERIC DEFAULT '2001-03-15',
"c6" NUMERIC DEFAULT '00:00:00.000',
"c7" NUMERIC DEFAULT '2001-03-15 00:00:00.000',
"c8" NUMERIC NULL,
"c9" INTEGER DEFAULT 1,
PRIMARY KEY("c1"]))>
[ERROR]   SqliteDatabaseDialectTest.shouldBuildUpsertStatement:193 expected:<...ERT OR REPLACE INTO [`myTable`(`id1`,`id2`,`columnA`,`columnB`,`columnC`,`columnD`]) VALUES(?,?,?,?,?,?...> but was:<...ERT OR REPLACE INTO ["myTable"("id1","id2","columnA","columnB","columnC","columnD"]) VALUES(?,?,?,?,?,?...>
[ERROR]   SqliteDatabaseDialectTest.upsert:238 expected:<...ERT OR REPLACE INTO [`Book`(`author`,`title`,`ISBN`,`year`,`pages`]) VALUES(?,?,?,?,?)> but was:<...ERT OR REPLACE INTO ["Book"("author","title","ISBN","year","pages"]) VALUES(?,?,?,?,?)>
[ERROR] Errors: 
[ERROR]   BufferedRecordsTest.correctBatching:99 » Config Unknown configuration 'batch.m...
[ERROR]   BufferedRecordsTest.insertThenDeleteInBatchNoFlush:166 » Config Unknown config...
[ERROR]   BufferedRecordsTest.insertThenDeleteThenInsertInBatchFlush:285 » Config Unknow...
[ERROR]   BufferedRecordsTest.insertThenDeleteWithSchemaThenInsertInBatchFlush:344 » Config
[ERROR]   BufferedRecordsTest.insertThenTwoDeletesWithSchemaInBatchNoFlush:226 » Config ...
[ERROR]   BufferedRecordsTest.testFlushSuccessNoInfo:514 » Config Unknown configuration ...
[ERROR]   BufferedRecordsTest.testInsertModeUpdate:553 » Config Unknown configuration 'b...
[ERROR]   BufferedRecordsTest.testMultipleDeletesBatchedTogether:404 » Config Unknown co...
[ERROR]   BufferedRecordsTest.testMultipleDeletesWithSchemaBatchedTogether:461 » Config ...
[ERROR]   JdbcDbWriterTest.autoCreateWithAutoEvolve:99 » Config Unknown configuration 'b...
[ERROR]   JdbcDbWriterTest.idempotentDeletes:237 » Config Unknown configuration 'batch.m...
[ERROR]   JdbcDbWriterTest.idempotentUpsertWithKafkaPk:136->writeSameRecordTwiceExpectingSingleUpdate:193 » Config
[ERROR]   JdbcDbWriterTest.idempotentUpsertWithRecordKeyPk:146->writeSameRecordTwiceExpectingSingleUpdate:193 » Config
[ERROR]   JdbcDbWriterTest.idempotentUpsertWithRecordValuePk:156->writeSameRecordTwiceExpectingSingleUpdate:193 » Config
[ERROR]   JdbcDbWriterTest.insertDeleteInsertSameRecord:329 » Config Unknown configurati...
[ERROR]   JdbcDbWriterTest.insertDeleteSameRecord:284 » Config Unknown configuration 'ba...
[ERROR]   JdbcDbWriterTest.multiInsertWithKafkaPkFailsDueToUniqueConstraint »  Unexpecte...
[ERROR]   JdbcDbWriterTest.multiInsertWithRecordKeyPkFailsDueToUniqueConstraint »  Unexp...
[ERROR]   JdbcDbWriterTest.multiInsertWithRecordValuePkFailsDueToUniqueConstraint »  Une...
[ERROR]   JdbcDbWriterTest.sameRecordNTimes:407 » Config Unknown configuration 'batch.ma...
[ERROR]   JdbcSinkTaskTest.putPropagatesToDbWithAutoCreateAndPkModeKafka:105 » Config Un...
[ERROR]   JdbcSinkTaskTest.putPropagatesToDbWithPkModeRecordValue:179 » Config Unknown c...
[INFO] 
[ERROR] Tests run: 551, Failures: 9, Errors: 22, Skipped: 2
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:21 min
[INFO] Finished at: 2020-02-03T08:59:59Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project kafka-connect-jdbc: There are test failures.
[ERROR] 
[ERROR] Please refer to /tmp/kafka-connect-jdbc-master/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
The command '/bin/sh -c curl https://github.com/confluentinc/kafka-connect-jdbc/archive/master.zip -L -o kafka-connect-jdbc.zip     && unzip kafka-connect-jdbc.zip -d /tmp/     && cd /tmp/kafka-connect-jdbc-master/     && mvn clean package' returned a non-zero code: 1
```

**Comment by gharris1727** [comment]
Master was failing, and was fixed by #784 .

**Comment by yohei1126** [comment]
@gharris1727 Tried it again but it still fails with the same errors. I will recreate the issue until the error is fixed.

**Comment by gharris1727** [comment]
Can you confirm that you're getting the newest version which includes the fix? Is it possible that your build is stale?

I just downloaded `master.zip` and confirmed that the fix is there, so i'm not sure how you're still getting the issue.

**Comment by yohei1126** [comment]
I have already provided the Dockerfile. See details in the description.

**Comment by yohei1126** [comment]
Can you build with the following conditions?

```
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 4.19
[INFO] os.detected.version.major: 4
[INFO] os.detected.version.minor: 19
[INFO] os.detected.release: ubuntu
[INFO] os.detected.release.version: 18.04
[INFO] os.detected.release.like.ubuntu: true
[INFO] os.detected.release.like.debian: true
[INFO] os.detected.classifier: linux-x86_64
```

**Comment by gharris1727** [comment]
Please re-run your build with `--no-cache` to make sure that you're not seeing caching effects.

**Comment by yohei1126** [comment]
@gharris1727 I tried it before but I tried it again then I got the same error. I used the same Dockerfile as I mentioned in the description.

```
$ docker build -t kafka-connect --no-cache .
...
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 4.19
[INFO] os.detected.version.major: 4
[INFO] os.detected.version.minor: 19
[INFO] os.detected.release: ubuntu
[INFO] os.detected.release.version: 18.04
[INFO] os.detected.release.like.ubuntu: true
[INFO] os.detected.release.like.debian: true
[INFO] os.detected.classifier: linux-x86_64
[INFO] 
[INFO] ------------------< io.confluent:kafka-connect-jdbc >-------------------
[INFO] Building kafka-connect-jdbc 5.5.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
...
INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.confluent.connect.jdbc.JdbcSourceConnectorTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.561 s - in io.confluent.connect.jdbc.JdbcSourceConnectorTest
[INFO] Running io.confluent.connect.jdbc.dialect.DerbyDatabaseDialectTest
[WARNING] Tests run: 29, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.108 s - in io.confluent.connect.jdbc.dialect.DerbyDatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialectTest
[INFO] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 s - in io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.dialect.SqlServerDatabaseDialectTest
[INFO] Tests run: 27, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.03 s - in io.confluent.connect.jdbc.dialect.SqlServerDatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.dialect.OracleDatabaseDialectTest
[INFO] Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in io.confluent.connect.jdbc.dialect.OracleDatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest
[ERROR] Tests run: 24, Failures: 9, Errors: 0, Skipped: 0, Time elapsed: 0.081 s <<< FAILURE! - in io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest
[ERROR] createThreeColTwoPk(io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest)  Time elapsed: 0.005 s  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<CREATE TABLE [`myTable` (
`pk1` INTEGER NOT NULL,
`pk2` INTEGER NOT NULL,
`col1` INTEGER NOT NULL,
PRIMARY KEY(`pk1`,`pk2`]))> but was:<CREATE TABLE ["myTable" (
"pk1" INTEGER NOT NULL,
"pk2" INTEGER NOT NULL,
"col1" INTEGER NOT NULL,
PRIMARY KEY("pk1","pk2"]))>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.createThreeColTwoPk(SqliteDatabaseDialectTest.java:211)

[ERROR] createOneColNoPk(io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest)  Time elapsed: 0 s  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<CREATE TABLE [`myTable` (
`col1`] INTEGER NOT NULL)> but was:<CREATE TABLE ["myTable" (
"col1"] INTEGER NOT NULL)>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.createOneColNoPk(SqliteDatabaseDialectTest.java:198)

[ERROR] alterAddOneCol(io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest)  Time elapsed: 0.002 s  <<< FAILURE!
org.junit.internal.ArrayComparisonFailure: arrays first differed at element [0]; expected:<ALTER TABLE [`myTable` ADD `newcol1`] INTEGER NULL> but was:<ALTER TABLE ["myTable" ADD "newcol1"] INTEGER NULL>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.alterAddOneCol(SqliteDatabaseDialectTest.java:226)
Caused by: org.junit.ComparisonFailure: expected:<ALTER TABLE [`myTable` ADD `newcol1`] INTEGER NULL> but was:<ALTER TABLE ["myTable" ADD "newcol1"] INTEGER NULL>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.alterAddOneCol(SqliteDatabaseDialectTest.java:226)

[ERROR] shouldBuildUpsertStatement(io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest)  Time elapsed: 0.001 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...ERT OR REPLACE INTO [`myTable`(`id1`,`id2`,`columnA`,`columnB`,`columnC`,`columnD`]) VALUES(?,?,?,?,?,?...> but was:<...ERT OR REPLACE INTO ["myTable"("id1","id2","columnA","columnB","columnC","columnD"]) VALUES(?,?,?,?,?,?...>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.shouldBuildUpsertStatement(SqliteDatabaseDialectTest.java:193)

[ERROR] alterAddTwoCol(io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest)  Time elapsed: 0.001 s  <<< FAILURE!
org.junit.internal.ArrayComparisonFailure: arrays first differed at element [0]; expected:<ALTER TABLE [`myTable` ADD `newcol1`] INTEGER NULL> but was:<ALTER TABLE ["myTable" ADD "newcol1"] INTEGER NULL>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.alterAddTwoCol(SqliteDatabaseDialectTest.java:231)
Caused by: org.junit.ComparisonFailure: expected:<ALTER TABLE [`myTable` ADD `newcol1`] INTEGER NULL> but was:<ALTER TABLE ["myTable" ADD "newcol1"] INTEGER NULL>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.alterAddTwoCol(SqliteDatabaseDialectTest.java:231)

[ERROR] upsert(io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest)  Time elapsed: 0.001 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...ERT OR REPLACE INTO [`Book`(`author`,`title`,`ISBN`,`year`,`pages`]) VALUES(?,?,?,?,?)> but was:<...ERT OR REPLACE INTO ["Book"("author","title","ISBN","year","pages"]) VALUES(?,?,?,?,?)>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.upsert(SqliteDatabaseDialectTest.java:238)

[ERROR] createOneColOnePk(io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest)  Time elapsed: 0.001 s  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<CREATE TABLE [`myTable` (
`pk1` INTEGER NOT NULL,
PRIMARY KEY(`pk1`]))> but was:<CREATE TABLE ["myTable" (
"pk1" INTEGER NOT NULL,
PRIMARY KEY("pk1"]))>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.createOneColOnePk(SqliteDatabaseDialectTest.java:204)

[ERROR] shouldBuildCreateQueryStatement(io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest)  Time elapsed: 0.002 s  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<CREATE TABLE [`myTable` (
`c1` INTEGER NOT NULL,
`c2` INTEGER NOT NULL,
`c3` TEXT NOT NULL,
`c4` TEXT NULL,
`c5` NUMERIC DEFAULT '2001-03-15',
`c6` NUMERIC DEFAULT '00:00:00.000',
`c7` NUMERIC DEFAULT '2001-03-15 00:00:00.000',
`c8` NUMERIC NULL,
`c9` INTEGER DEFAULT 1,
PRIMARY KEY(`c1`]))> but was:<CREATE TABLE ["myTable" (
"c1" INTEGER NOT NULL,
"c2" INTEGER NOT NULL,
"c3" TEXT NOT NULL,
"c4" TEXT NULL,
"c5" NUMERIC DEFAULT '2001-03-15',
"c6" NUMERIC DEFAULT '00:00:00.000',
"c7" NUMERIC DEFAULT '2001-03-15 00:00:00.000',
"c8" NUMERIC NULL,
"c9" INTEGER DEFAULT 1,
PRIMARY KEY("c1"]))>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.shouldBuildCreateQueryStatement(SqliteDatabaseDialectTest.java:120)

[ERROR] shouldBuildAlterTableStatement(io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest)  Time elapsed: 0.001 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<ALTER TABLE [`myTable` ADD `c1`] INTEGER NOT NULL> but was:<ALTER TABLE ["myTable" ADD "c1"] INTEGER NOT NULL>
        at io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest.shouldBuildAlterTableStatement(SqliteDatabaseDialectTest.java:155)

[INFO] Running io.confluent.connect.jdbc.dialect.SapHanaDatabaseDialectTest
[INFO] Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in io.confluent.connect.jdbc.dialect.SapHanaDatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.dialect.VerticaDatabaseDialectTest
[INFO] Tests run: 22, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 s - in io.confluent.connect.jdbc.dialect.VerticaDatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.dialect.MySqlDatabaseDialectTest
[INFO] Tests run: 27, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.138 s - in io.confluent.connect.jdbc.dialect.MySqlDatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.dialect.DatabaseDialectsTest
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in io.confluent.connect.jdbc.dialect.DatabaseDialectsTest
[INFO] Running io.confluent.connect.jdbc.dialect.GenericDatabaseDialectTest
[INFO] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.864 s - in io.confluent.connect.jdbc.dialect.GenericDatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.dialect.SybaseDatabaseDialectTest
[INFO] Tests run: 27, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.092 s - in io.confluent.connect.jdbc.dialect.SybaseDatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.dialect.GenericDatabaseDialectTypeTest
[INFO] Tests run: 36, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.039 s - in io.confluent.connect.jdbc.dialect.GenericDatabaseDialectTypeTest
[INFO] Running io.confluent.connect.jdbc.dialect.Db2DatabaseDialectTest
[INFO] Tests run: 31, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 s - in io.confluent.connect.jdbc.dialect.Db2DatabaseDialectTest
[INFO] Running io.confluent.connect.jdbc.sink.DbStructureTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in io.confluent.connect.jdbc.sink.DbStructureTest
[INFO] Running io.confluent.connect.jdbc.sink.BufferedRecordsTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.051 s - in io.confluent.connect.jdbc.sink.BufferedRecordsTest
[INFO] Running io.confluent.connect.jdbc.sink.PreparedStatementBinderTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in io.confluent.connect.jdbc.sink.PreparedStatementBinderTest
[INFO] Running io.confluent.connect.jdbc.sink.metadata.FieldsMetadataTest
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in io.confluent.connect.jdbc.sink.metadata.FieldsMetadataTest
[INFO] Running io.confluent.connect.jdbc.sink.JdbcSinkTaskTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.075 s - in io.confluent.connect.jdbc.sink.JdbcSinkTaskTest
[INFO] Running io.confluent.connect.jdbc.sink.JdbcDbWriterTest
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.181 s - in io.confluent.connect.jdbc.sink.JdbcDbWriterTest
[INFO] Running io.confluent.connect.jdbc.sink.SqliteHelperTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 s - in io.confluent.connect.jdbc.sink.SqliteHelperTest
[INFO] Running io.confluent.connect.jdbc.util.ExpressionBuilderTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in io.confluent.connect.jdbc.util.ExpressionBuilderTest
[INFO] Running io.confluent.connect.jdbc.util.IdentifierRulesTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in io.confluent.connect.jdbc.util.IdentifierRulesTest
[INFO] Running io.confluent.connect.jdbc.util.TimeZoneValidatorTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in io.confluent.connect.jdbc.util.TimeZoneValidatorTest
[INFO] Running io.confluent.connect.jdbc.util.CachedConnectionProviderTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.877 s - in io.confluent.connect.jdbc.util.CachedConnectionProviderTest
[INFO] Running io.confluent.connect.jdbc.source.TimestampIncrementingCriteriaTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 s - in io.confluent.connect.jdbc.source.TimestampIncrementingCriteriaTest
[INFO] Running io.confluent.connect.jdbc.source.JdbcSourceTaskUpdateTest
[INFO] Tests run: 26, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.026 s - in io.confluent.connect.jdbc.source.JdbcSourceTaskUpdateTest
[INFO] Running io.confluent.connect.jdbc.source.JdbcSourceTaskLifecycleTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.638 s - in io.confluent.connect.jdbc.source.JdbcSourceTaskLifecycleTest
[INFO] Running io.confluent.connect.jdbc.source.JdbcSourceTaskConversionTest
[INFO] Tests run: 62, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.521 s - in io.confluent.connect.jdbc.source.JdbcSourceTaskConversionTest
[INFO] Running io.confluent.connect.jdbc.source.JdbcSourceConnectorConfigTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.347 s - in io.confluent.connect.jdbc.source.JdbcSourceConnectorConfigTest
[INFO] Running io.confluent.connect.jdbc.source.TableQuerierTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in io.confluent.connect.jdbc.source.TableQuerierTest
[INFO] Running io.confluent.connect.jdbc.source.TableMonitorThreadTest
Exception in thread "Thread-90" org.apache.kafka.connect.errors.ConnectException: Simulated error with the db.
        at io.confluent.connect.jdbc.source.TableMonitorThreadTest$1.answer(TableMonitorThreadTest.java:164)
        at io.confluent.connect.jdbc.source.TableMonitorThreadTest$1.answer(TableMonitorThreadTest.java:160)
        at org.easymock.internal.Result.answer(Result.java:133)
        at org.easymock.internal.ReplayState.invokeInner(ReplayState.java:61)
        at org.easymock.internal.ReplayState.invoke(ReplayState.java:47)
        at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:40)
        at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:101)
        at com.sun.proxy.$Proxy32.getConnection(Unknown Source)
        at io.confluent.connect.jdbc.source.TableMonitorThread.updateTables(TableMonitorThread.java:141)
        at io.confluent.connect.jdbc.source.TableMonitorThread.run(TableMonitorThread.java:76)
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.394 s - in io.confluent.connect.jdbc.source.TableMonitorThreadTest
[INFO] Running io.confluent.connect.jdbc.source.NumericMappingConfigTest
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s - in io.confluent.connect.jdbc.source.NumericMappingConfigTest
[INFO] Running io.confluent.connect.jdbc.source.TimestampIncrementingOffsetTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in io.confluent.connect.jdbc.source.TimestampIncrementingOffsetTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SqliteDatabaseDialectTest.alterAddOneCol:226->BaseDialectTest.verifyAlterAddOneCol:398 arrays first differed at element [0]; expected:<ALTER TABLE [`myTable` ADD `newcol1`] INTEGER NULL> but was:<ALTER TABLE ["myTable" ADD "newcol1"] INTEGER NULL>
[ERROR]   SqliteDatabaseDialectTest.alterAddTwoCol:231->BaseDialectTest.verifyAlterAddTwoCols:404 arrays first differed at element [0]; expected:<ALTER TABLE [`myTable` ADD `newcol1`] INTEGER NULL> but was:<ALTER TABLE ["myTable" ADD "newcol1"] INTEGER NULL>
[ERROR]   SqliteDatabaseDialectTest.createOneColNoPk:198->BaseDialectTest.verifyCreateOneColNoPk:372 expected:<CREATE TABLE [`myTable` (
`col1`] INTEGER NOT NULL)> but was:<CREATE TABLE ["myTable" (
"col1"] INTEGER NOT NULL)>
[ERROR]   SqliteDatabaseDialectTest.createOneColOnePk:204->BaseDialectTest.verifyCreateOneColOnePk:378 expected:<CREATE TABLE [`myTable` (
`pk1` INTEGER NOT NULL,
PRIMARY KEY(`pk1`]))> but was:<CREATE TABLE ["myTable" (
"pk1" INTEGER NOT NULL,
PRIMARY KEY("pk1"]))>
[ERROR]   SqliteDatabaseDialectTest.createThreeColTwoPk:211->BaseDialectTest.verifyCreateThreeColTwoPk:390 expected:<CREATE TABLE [`myTable` (
`pk1` INTEGER NOT NULL,
`pk2` INTEGER NOT NULL,
`col1` INTEGER NOT NULL,
PRIMARY KEY(`pk1`,`pk2`]))> but was:<CREATE TABLE ["myTable" (
"pk1" INTEGER NOT NULL,
"pk2" INTEGER NOT NULL,
"col1" INTEGER NOT NULL,
PRIMARY KEY("pk1","pk2"]))>
[ERROR]   SqliteDatabaseDialectTest.shouldBuildAlterTableStatement:155->BaseDialectTest.assertStatements:350 expected:<ALTER TABLE [`myTable` ADD `c1`] INTEGER NOT NULL> but was:<ALTER TABLE ["myTable" ADD "c1"] INTEGER NOT NULL>
[ERROR]   SqliteDatabaseDialectTest.shouldBuildCreateQueryStatement:120 expected:<CREATE TABLE [`myTable` (
`c1` INTEGER NOT NULL,
`c2` INTEGER NOT NULL,
`c3` TEXT NOT NULL,
`c4` TEXT NULL,
`c5` NUMERIC DEFAULT '2001-03-15',
`c6` NUMERIC DEFAULT '00:00:00.000',
`c7` NUMERIC DEFAULT '2001-03-15 00:00:00.000',
`c8` NUMERIC NULL,
`c9` INTEGER DEFAULT 1,
PRIMARY KEY(`c1`]))> but was:<CREATE TABLE ["myTable" (
"c1" INTEGER NOT NULL,
"c2" INTEGER NOT NULL,
"c3" TEXT NOT NULL,
"c4" TEXT NULL,
"c5" NUMERIC DEFAULT '2001-03-15',
"c6" NUMERIC DEFAULT '00:00:00.000',
"c7" NUMERIC DEFAULT '2001-03-15 00:00:00.000',
"c8" NUMERIC NULL,
"c9" INTEGER DEFAULT 1,
PRIMARY KEY("c1"]))>
[ERROR]   SqliteDatabaseDialectTest.shouldBuildUpsertStatement:193 expected:<...ERT OR REPLACE INTO [`myTable`(`id1`,`id2`,`columnA`,`columnB`,`columnC`,`columnD`]) VALUES(?,?,?,?,?,?...> but was:<...ERT OR REPLACE INTO ["myTable"("id1","id2","columnA","columnB","columnC","columnD"]) VALUES(?,?,?,?,?,?...>
[ERROR]   SqliteDatabaseDialectTest.upsert:238 expected:<...ERT OR REPLACE INTO [`Book`(`author`,`title`,`ISBN`,`year`,`pages`]) VALUES(?,?,?,?,?)> but was:<...ERT OR REPLACE INTO ["Book"("author","title","ISBN","year","pages"]) VALUES(?,?,?,?,?)>
[INFO] 
[ERROR] Tests run: 551, Failures: 9, Errors: 0, Skipped: 2
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:37 min
[INFO] Finished at: 2020-02-04T23:45:50Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project kafka-connect-jdbc: There are test failures.
[ERROR] 
[ERROR] Please refer to /tmp/kafka-connect-jdbc-master/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
The command '/bin/sh -c curl https://github.com/confluentinc/kafka-connect-jdbc/archive/master.zip -L -o kafka-connect-jdbc.zip     && unzip kafka-connect-jdbc.zip -d /tmp/     && cd /tmp/kafka-connect-jdbc-master/     && mvn clean package' returned a non-zero code: 1
```

**Comment by yohei1126** [comment]
I can not see how you are building on Jenkins. You do not support build on Ubuntu 18.04?
Which Docker image or Linux distribution are you using for build?

**Comment by gharris1727** [comment]
I highly doubt that this is an environment issue, since the dockerfile is built inside of another docker container. It's also an internal build problem, not some networking or dependency issue.

You're somehow getting a stale version of the code, but I dont know how. You need to debug on your own to find out why it's stale, I can't help since I can't reproduce your issue.

**Comment by yohei1126** [comment]
I am asking Which Docker image or Linux distribution are you using for build?

**Comment by yohei1126** [comment]
The build work on my mac book.

```
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.15
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 15
[INFO] os.detected.classifier: osx-x86_64
[INFO] ------------------------------------------------------------------------
```

**Comment by gharris1727** [comment]
Sorry, I didn't notice that the error changed between your two messages.
The error message is now with some quoting logic, and not with the missing configuration that was fixed in a recent PR.

We build docker images for these with debian 8 most often, but that build doesn't run for this repository.

**Comment by Schmidt96u** [comment]
I found the same issue while building with maven.

This is my configuration : 

Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 5.3
[INFO] os.detected.version.major: 5
[INFO] os.detected.version.minor: 3
[INFO] os.detected.release: ubuntu
[INFO] os.detected.release.version: 18.04
[INFO] os.detected.release.like.ubuntu: true
[INFO] os.detected.release.like.debian: true
[INFO] os.detected.classifier: linux-x86_64


And the Test 24 come up with : 

![Screenshot from 2020-03-09 10-16-27](https://user-images.githubusercontent.com/43668516/76538954-61f10b80-6480-11ea-90fd-230c59fb9d21.png)



The error comes from the use of  ` . 

Two main reasons are possible  : 

First, under SQLite it’s not recommended to use backticks. It was added only to be compatible with mySQL. It’s better to use double-quote rather than backticks https://www.sqlite.org/lang_keywords.html (possible)
Configuration issues, and compatibility issues between Linux and Mac OS . (less possible).

I fixed this issue by changing the test 24. (change characters backticks to double quote).

And it’s was working : 



I submit a pull request https://github.com/confluentinc/kafka-connect-jdbc/pull/812

**Comment by chrisVia** [comment]
Hi, we're running into this issue as well as we've been looking to contribute changes to this project. It's puzzling to me that the project build uses maven, and yet the project cannot be built from the official maven docker image due to this lingering issue with back-ticks vs double-quotes for the SqliteDatabaseDialectTest class. Can developers share what environment they are using to actually build this project, and perhaps what is the underlying reason we are running into this issue? We're seeing this using the official `maven:3.6.3-openjdk-14-slim` image.

```
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 4.19
[INFO] os.detected.version.major: 4
[INFO] os.detected.version.minor: 19
[INFO] os.detected.release: debian
[INFO] os.detected.release.version: 10
[INFO] os.detected.release.like.debian: true
[INFO] os.detected.classifier: linux-x86_64
```

and specifically: `mvn -Dtest=io.confluent.connect.jdbc.dialect.SqliteDatabaseDialectTest test -Dmaven.buildNumber.revisionOnScmFailure=no-scm`

#812 Can't be accepted generally because just flipping stuff from backticks to double-quotes now just introduces the inverse failures in a different build-environment (presumably the one actually been used for the project's continuous-integration)

**Comment by OneCricketeer** [comment]
Unless you actually need a latest patch/commit, why not use `confluent-hub` to install the latest, production supported release? Or check out a release tag rather than build master?
