### ISSUE TITLE
No matching ce-kafka version found for constraint: 'org.apache.kafka:kafka-clients::[6.1.0-0, 6.1.1-0), excluding snapshots'

### ISSUE THREAD

**Issue by Yosafat1997** [confluentinc/kafka-connect-jdbc#911]
I want to test the request merge from this pull https://github.com/confluentinc/kafka-connect-jdbc/pull/805 for my project before someone approve the merge.

I have follow the step to prepare my environment (which is ```home/<<my_user>>/.m2/repository```):

```
git clone https://github.com/confluentinc/kafka.git
cd kafka/
./gradlewAll install
cd ..
git clone https://github.com/confluentinc/common.git
cd common/
mvn install
```
But at the end, i got this error:
```
[WARNING] The POM for io.confluent:resolver-maven-plugin:jar:0.4.0 is missing, no dependency information available
Downloading from confluent: http://packages.confluent.io/maven/io/confluent/resolver-maven-plugin/0.4.0/resolver-maven-plugin-0.4.0.jar
Downloading from central: https://repo.maven.apache.org/maven2/io/confluent/resolver-maven-plugin/0.4.0/resolver-maven-plugin-0.4.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for common 6.1.0-SNAPSHOT:
[INFO] 
[INFO] assembly-plugin-boilerplate ........................ SUCCESS [01:05 min]
[INFO] Build Tools ........................................ SUCCESS [ 57.638 s]
[INFO] common ............................................. FAILURE [ 22.979 s]
[INFO] utils .............................................. SKIPPED
[INFO] metrics ............................................ SKIPPED
[INFO] config ............................................. SKIPPED
[INFO] common-logging ..................................... SKIPPED
[INFO] confluent-log4j-extensions ......................... SKIPPED
[INFO] confluent-log4j2-extensions ........................ SKIPPED
[INFO] package ............................................ SKIPPED
[INFO] Common ............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:03 min
[INFO] Finished at: 2020-08-31T15:07:37+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin io.confluent:resolver-maven-plugin:0.4.0 or one of its dependencies could not be resolved: Could not find artifact io.confluent:resolver-maven-plugin:jar:0.4.0 in confluent (http://packages.confluent.io/maven/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```
Sorry, I still new in maven development cycle and still learn about it. But due some reason, this merge request are very useful for us when we deal with advance datatype such as array. So, I intend to test it with my own environment, get the build jar and test it on real case.

Kafka Version pulled = 6.1.0-0-ccs
common_version = pulled from master (6.1.0-SNAPSHOT)

**Comment by Yosafat1997** [comment]
#805

**Comment by Yosafat1997** [comment]
Any update about this?

**Comment by Yosafat1997** [comment]
UPDATE:


i have install the resolver that needed for common and use 0.4.0 version buta when i install common, it give me this error:
```
[ERROR] Failed to execute goal io.confluent:resolver-maven-plugin:0.4.0:resolve-kafka-range (default) on project common-parent: : MojoExecutionException: No matching ce-kafka version found for constraint: 'org.apache.kafka:kafka-clients::[6.1.0-0, 6.1.1-0), excluding snapshots'. -> [Help 1]
```
my repository structure are like this: 
|_.m2\
   |_repository\
          |_resolver-maven-plugin\
          |_kafka\
             |_common\
```

Is there something wrong i missing?

**Comment by Yosafat1997** [comment]
- [ Investigate issue on depedency in Kafka and Common ]

**Comment by Yosafat1997** [comment]
Update: this is i Found when run common mvn install -X :
```
[DEBUG] ce-kafka version fetched [6.1.0-0-ccs]
[INFO] ce-kafka can not be fetched
[DEBUG] ce-kafka Constraint: [6.1.0-0,6.1.1-0)
[DEBUG] ce-kafka Versions in range: []
```
i don't know why ce-kafka version for this one is cannot be fetched even i have build it in my local repo?

**Comment by Yosafat1997** [comment]
If there're someone has same problem with me and have the fix, plese mention your fix here.

**Comment by xjrk58** [comment]
@Yosafat1997 there is not a single 6.x.x version available publicly for common or kafka-connect-jdbc projects. And common project has only v6.1.x non-beta versions available in github.

**Comment by elismaga** [comment]
@Yosafat1997 I am working on a fix for this issue and hope to have something merged by Monday. As a temporary work around is it possible for you to do your testing using the 6.0.0 release? If so you can check out the corresponding branch of the kafka repo and then check out the 6.0.x branch of the common repo and build using that. You will not hit this issue using the 6.0.0 version.

**Comment by Yosafat1997** [comment]
So using 6.0.x version of common then version 6.0.x corespondenting kafka. Okay i will try that

**Comment by elismaga** [comment]
@Yosafat1997 I have merged a fix to the common repo for this. Can you please pull down the latest version common master branch and let me know if it works for you.

**Comment by Yosafat1997** [comment]
Sure

**Comment by Yosafat1997** [comment]
@elismaga it's still happen, actually what kafka version does needed? I use branch ```v6.1.0-beta200825192044-hf-1``` and get this:

```
[DEBUG] ce-kafka version fetched [6.1.0-ccs-beta200825192044-hf-1, 6.1.0-0-ccs]
[INFO] ce-kafka can not be fetched
[DEBUG] ce-kafka Constraint: [6.1.0-0,6.1.1-0)
[DEBUG] ce-kafka Versions in range: []
```

**Comment by elismaga** [comment]
@Yosafat1997 I thought you were building from the master branch of both repos. Can you try that? Also, what you pasted isn't causing an error this time, those are just info and debug messages. Can you send me the error and or exception you got.

**Comment by Yosafat1997** [comment]
@elismaga thanks, it works now. I have modified a little from @Faqa pull #805  and i test it for postgres and it works. Need time to request pull and merge my works with current kafka-connect jdbc
